env:
  es6: true
  es2020: true
  jest/globals: true
  node: true
extends:
  # I want to know the best practices for the settings here.
  # I don't know it, but this so many extends are enough to make it feel non-exemplary.
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
globals:
  window: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '*.config.?s'
        - '**/*.spec.?s'
        - 'sample/*.?s'
  no-console:
    - warn
settings:
  import/resolver:
    node:
    webpack:
      config: webpack.config.ts
