env:
  es6: true
  es2020: true
  jest/globals: true
  node: true
extends:
  - airbnb-base
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'
  - prettier/@typescript-eslint
globals:
  window: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - jest
  - prettier
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '*.config.?s'
        - '**/*.spec.?s'
        - 'sample/*.?s'
  no-console:
    - warn
settings:
  import/resolver:
    node:
    webpack:
      config: webpack.config.ts
