plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file. See
        [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
  - - '@semantic-release/npm'
    - tarballDir: pack
  - - '@semantic-release/github'
    - assets: pack/*.tgz
  - - '@semantic-release/git'
    - message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
